version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached       # Mount project code for live reload
      - vendor:/var/www/html/vendor  # Named volume for dependencies
    ports:
      - "8000:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      # CMD from Dockerfile is used by default

volumes:
  vendor: